### PR TITLE
Run build step in Orka as privilege

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

To run Orka in OpenShift successfully we need to run the build step as privileged else some operations are not permitted without privilege access

Signed-off-by: vinamra28 <vinjain@redhat.com>
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by piyush-garg** [comment]
cc @spikeburton @ispasov @Tmoss11

**Comment by afrittoli** [comment]
> Approvers can cancel approval by writing `/approve cancel` in a comment

Uhm, according to the [approve plugin docs](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/approve/approvers/README.md#example) the OWNER file in https://github.com/tektoncd/catalog/blob/c480135d951072c9f1f9a57e3065d7afdf26e4db/task/orka-full/OWNERS#L2
should apply 😕

**Pull request merged**
