### PR TITLE
[tasks/maven] Support to repository cache

### PR DESCRIPTION
**Pull request by crmarques**
# Changes

Support to use a persistent volume to hold downloaded maven artifacts, avoiding unnecessary resource consumption.

### CODE REVIEW

**Comment by chmouel** [comment]
I think you mean 0.4 in your commit message

the diff https://paste.gg/p/anonymous/0659c8df83044ad4aefe97deab3c52d5

/ok-to-test

**Comment by chmouel** [comment]
I see you are using a volume, what about a optional workspace instead?

**Comment by crmarques** [comment]
Hi, @chmouel . Thank you for your response. I agree with you about using workspaces. It was my initial thought. But I saw this volume/podTemplate implementation in `jib-maven` and  `buildpacks:0.1` Tasks and imagined that was the recommendation.

I'll change it to workspace and update this PR.

**Comment by tuananh** [comment]
if we want to use `git-clone` task with this, it will fail because there's more than 1 PVC right? `more than one PersistentVolumeClaim is bound`

**Comment by tuananh** [comment]
to get it to work, you will need to set `disable-affinity-assistant` to `true`.

**Pull request closed without merging**
