### PR TITLE
Update paketo builders location to dockerhub

### PR DESCRIPTION
**Pull request by dumez-k**
[#173928543]

# Changes

Update paketo builders location to dockerhub

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x ] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.
- [x ] Complies with [Catalog Orgainization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by chmouel** [comment]
/ok-to-test
/lgtm

Thanks for your contribution, feel free to go over the easy-cla signing process and we are good to go 👍

**Comment by dumez-k** [comment]
@jromero Finally got the CLA sorted. This should be good to go, but let's definitely chat about that process sometime.

**Pull request merged**
