### PR TITLE
Update openshift client task to use script mode

### PR DESCRIPTION
**Pull request by piyush-garg**
This will update openshift-client to be used in script mode

This will help to pass multiple commands or parametrized
commands in a single taskrun

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by piyush-garg** [comment]
@vdemeester I think we should keep the old one also, so that it may not affect the users who are using this.

**Comment by piyush-garg** [comment]
We can do that, but that is adding no value.

Do you see any value with adding a new param `SCRIPT`?

We are adding the SCRIPT task to support multiple commands in task like

```
oc rollout latest myapp
oc rollout status myapp
```

**Comment by vdemeester** [comment]
> We can do that, but that is adding no value.
> 
> Do you see any value with adding a new param `SCRIPT`?
> 
> We are adding the SCRIPT task to support multiple commands in a task like
> 
> ```
> oc rollout latest myapp
> oc rollout status myapp
> ```

well, actually it can add some making a Pipeline a little bit more re-usable. (This is a simple case)

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  params:
  - name: app
    description: app of the pipeline
  tasks:
  - name:foo
    taskRef:
      name: unit-tests
    resources:
      params:
      - name: ARGS
        value: $(params.app)
      - name: SCRIPT
        value: |
          oc rollout latest $1
          oc rollout status $1
```

**Comment by piyush-garg** [comment]
That way, we can find many cases like, a user needs two args or a user need some resource and so on. I am still not sure about changing the current tasks

**Comment by piyush-garg** [comment]
@vdemeester I have updated the PR. Please have a look.

**Pull request merged**
