### PR TITLE
Add diff-task-version script

### PR DESCRIPTION
**Pull request by chmouel**
Using github.com/cli/cli it takes a PR URL as first argument and check
it out.

It will then detect automatically the old and new version and post a
comment to the PR with the diff and copy it in your clipboard (with
xclip on Linux and pbcopy on OSX)

Signed-off-by: Chmouel Boudjnah <chmouel@redhat.com>

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
Next step is to use this as part of the CI and have the bot do it for us :)

**Comment by chmouel** [comment]
Next step would be to handle the edge cases, it's not robust enough for automatic ci yet

**Comment by chmouel** [comment]
@tektoncd/catalog-maintainers  +1 or -1?

**Pull request merged**
