### PR TITLE
Add parallelisation of tests

### PR DESCRIPTION
**Pull request by chmouel**
# Changes

We were running previously the tests sequentially,

Since the catalogs tests are growing exponentially, let's add parallelisation to
speed things up (default: 5 tests)

Moreover we add another related patch to be able to redefine KUBECONFIG for downstream CIs.

/area testing

### CODE REVIEW

**Comment by chmouel** [comment]
TIL the KUBECTL is already defined in other part of the scripts

```
++ KUBECTL='./cluster/kubectl.sh --match-server-version'
```

but we can't quite use it it seems because humm it's humm non existent 🤦 

using `KUBECTL_CMD` variable instead,

**Comment by chmouel** [comment]
Added  7bd7cb8  to make sure this PR it works (since it would skip things up if it cannot detect any test changes)

**Comment by chmouel** [comment]
Maven task is again flaky ! but this works and run tasks 5 by 5

**Review by vdemeester — APPROVED** [review]

**Review by vinamra28 — APPROVED** [review]
/lgtm

**Pull request merged**
