### PR TITLE
Add '42Crunch REST API Static Security Testing' task to the catalog

### PR DESCRIPTION
**Pull request by ak1394**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations][authoring]
- [x] Includes [docs][docs] (if user facing)
- [ ] Includes [tests][tests] (for new tasks or changed functionality)
  - See the [end-to-end testing documentation][e2e] for guidance and CI details.
- [x] Meets the [Tekton contributor standards][contributor] (including functionality, content, code)
- [x] Commit messages follow [commit message best practices][commit]
- [x] Has a kind label. You can add one by adding a comment on this PR that
  contains `/kind <type>`. Valid types are bug, cleanup, design, documentation,
  feature, flake, misc, question, tep
- [x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md) for more details._

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]: https://github.com/tektoncd/catalog/issues/413
[authoring]: https://github.com/tektoncd/catalog/blob/main/recommendations.md
[docs]: https://github.com/tektoncd/community/blob/master/standards.md#docs
[tests]: https://github.com/tektoncd/community/blob/master/standards.md#tests
[e2e]: https://github.com/tektoncd/catalog/blob/main/CONTRIBUTING.md#end-to-end-testing
[contributor]: https://github.com/tektoncd/community/blob/main/standards.md
[commit]: https://github.com/tektoncd/community/blob/master/standards.md#commit-messages

### CODE REVIEW

**Comment by ak1394** [comment]
@vinamra28 @vdemeester guys, I did a PR to add myself to the org: https://github.com/tektoncd/community/pull/869 but I still see 'invalid-owners-file' label. Is there anything else I need to do?

**Comment by vinamra28** [comment]
@ak1394, I just noticed, did you accept the invite that you might have received from Tekton to join the organization? If not, can you please do that?

**Comment by ak1394** [comment]
@ vinamra28 indeed! Thanks for pointing that out. I've joined the org now.

**Comment by ak1394** [comment]
@vinamra28 Thanks! Looks good now.

**Comment by ak1394** [comment]
@chmouel @vinamra28 Guys, do you need anything else from my end to merge this?

**Review by vinamra28 — APPROVED** [review]

**Comment by vinamra28** [comment]
@ak1394 can you please squash the commits and then we can go ahead and merge this?

**Comment by ak1394** [comment]
@vinamra28 thanks a lot! Squashed.

**Pull request merged**
