### PR TITLE
bumping up pipeline version

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

Tekton Pipeline [0.18.0](https://github.com/tektoncd/pipeline/releases/tag/v0.18.0) was just released and as part of the release [process](https://github.com/tektoncd/pipeline/pull/3258), bumping up the following images in the catalog tasks:

* (task - current images)
* git-batch-merge - v0.17.3
* git-clone - v0.17.3

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by pritidesai** [comment]
/hold 
@vinamra28 please take a look, I am put on a hold until we are sure about this change 🙏

**Review by vinamra28 — CHANGES_REQUESTED** [review]
hi @pritidesai, thanks for the PR :+1: 
I see in the latest pipeline release that there is a bug fix in the `git-init` binary https://github.com/tektoncd/pipeline/issues/3320. So probably we can just bump the image version of the `git-clone` and `git-batch-merge` tasks and avoid bumping the images for other tasks.

**Comment by pritidesai** [comment]
@vinamra28 I have updated this PR to include two packages and `e2e` tests. PTAL and feel free to remove hold if needed.

**Comment by vinamra28** [comment]
Thanks @pritidesai :+1: 
/lgtm
/hold cancel

**Comment by chmouel** [comment]
/lgtm
/approve

Thanks 👍🏼🔥

**Pull request merged**
