### PR TITLE
Add task to label Github pull request or an issue

### PR DESCRIPTION
**Pull request by Divyansh42**
# Changes

This task can be used to add labels to a Github `pull request` or an `issue`.

Signed-off-by: Divyansh42 <diagrawa@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.

### CODE REVIEW

**Comment by vdemeester** [comment]
@Divyansh42 how does it differ from [`pullrequest`](https://github.com/tektoncd/catalog/tree/v1beta1/pullrequest) ?

**Comment by Divyansh42** [comment]
> @Divyansh42 how does it differ from [`pullrequest`](https://github.com/tektoncd/catalog/tree/v1beta1/pullrequest) ?

This task is not very specific to `pull request` only. This can be used to add label to Issue also.

**Comment by Divyansh42** [comment]
> > @Divyansh42 how does it differ from [`pullrequest`](https://github.com/tektoncd/catalog/tree/v1beta1/pullrequest) ?
> 
> This task is not very specific to `pull request` only. This can be used to add label to Issue also.

@vdemeester is that sounds good to you? In similar way as we have task to [add-comment](https://github.com/tektoncd/catalog/blob/v1beta1/github/add_comment.yaml)  to PR and issue.

**Comment by vdemeester** [comment]
Make sense. We should try to keep the layout flat but I think it can "wait" for the Tekton Catalog organization design doc to be adopted.

/lgtm

**Pull request merged**
