### PR TITLE
Use environment variables in github-set-status

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Rather than using params in the script, set environment variables
and use them in the python script with os.getenv

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by afrittoli** [comment]
Not tested yet

**Comment by afrittoli** [comment]
@tektoncd/catalog-maintainers any suggestion on how to test this? There are no tests defined today for this task and I'm not comfortable changing it without any CI test. I see a couple of options:

- test the python script standalone and inject it back into the task
- run some kind of stub for the github api and run the task pointing to the stub api. Use a pipeline and use the next task to check that the stub received the correct request

Both would require a certain amount of work so I wanted to check if there was any preference / existing solution for this.

**Comment by vinamra28** [comment]
> @tektoncd/catalog-maintainers any suggestion on how to test this? There are no tests defined today for this task and I'm not comfortable changing it without any CI test. I see a couple of options:
> 
> * test the python script standalone and inject it back into the task
> * run some kind of stub for the github api and run the task pointing to the stub api. Use a pipeline and use the next task to check that the stub received the correct request
> 
> Both would require a certain amount of work so I wanted to check if there was any preference / existing solution for this.

@afrittoli maybe we can follow the process of writing tests we use for other related tasks such as [`github-add-comment`](https://github.com/tektoncd/catalog/tree/main/task/github-add-comment/0.7/tests)

**Comment by afrittoli** [comment]
> > @tektoncd/catalog-maintainers any suggestion on how to test this? There are no tests defined today for this task and I'm not comfortable changing it without any CI test. I see a couple of options:
> > 
> > * test the python script standalone and inject it back into the task
> > * run some kind of stub for the github api and run the task pointing to the stub api. Use a pipeline and use the next task to check that the stub received the correct request
> > 
> > Both would require a certain amount of work so I wanted to check if there was any preference / existing solution for this.
> 
> @afrittoli maybe we can follow the process of writing tests we use for other related tasks such as [`github-add-comment`](https://github.com/tektoncd/catalog/tree/main/task/github-add-comment/0.7/tests)

Sounds good, thanks @vinamra28

**Comment by chmouel** [comment]
I think the python script extraction is interesting.. may generally not work shell but if we are able to have python test for python based tasks which can then monkeypatch api call the it should make things much more robusts.

the https://github.com/chmouel/go-rest-api-test is fine too (or at least in this case) but we are generally limited to tasks that can communicate to http service....

**Review by vinamra28 — APPROVED** [review]
/lgtm
Thank you for doing this 🙂

**Pull request merged**
