### PR TITLE
OpenWhisk Deployment with Conditions

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

Adding tekton resources such as `conditions`, `pipeline`, and
`pipelinerun` with updated `openwhisk.yaml` so that the
deployment can pull entire github repo with the application source,
install necessary dependencies, archive the source with its dependencies,
and inject base64 encoded data into OpenWhisk runtime.

Note that, have added `openwhisk.yaml` under `runtimes/javascript/` since
Tekton Pipeline does not yet support optional pipeline resources such as,
this is tracked as part of https://github.com/tektoncd/pipeline/issues/812
once this is fixed, will update original `openwhisk.yaml`

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by sbwsg** [comment]
@pritidesai This PR needs a rebase, would you still like to pursue it?

I'm not familiar enough with openwhisk to offer in-depth review but I'm happy to visually validate the YAML.  Do you have anyone who you could bring in to review the technical content?

**Comment by pritidesai** [comment]
Yup, I have more changes to the pipeline, debating whether to close this PR and open a new or submit changes in this PR 🤔

**Comment by pritidesai** [comment]
I am closing this for now and will open a new PR with updates for Beta and two more runtimes (Java and Python) ...

**Pull request closed without merging**
