### PR TITLE
Bump images to 0.16.2

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

Signed-off-by: vinamra28 <vinjain@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Review by Divyansh42 — APPROVED** [review]
/lgtm

**Review by piyush-garg — APPROVED** [review]
/lgtm

**Review by vdemeester — COMMENTED** [review]
This is where we need to decide that a bump of `image` bumps the version of the task :upside_down_face: :wink: (or not)

cc @sthaha @chmouel @bobcatfish @sbwsg

**Comment by piyush-garg** [comment]
> This is where we need to decide that a bump of `image` bumps the version of the task   (or not)
> 
> cc @sthaha @chmouel @bobcatfish @sbwsg

If there is no breaking change, then it is fine to just bump the image in the same version afait.

Like for git-init, there was some breaking change in 0.14 so we bumped the task version, if there is no breaking then just bumping the image is fine I think

**Comment by bobcatfish** [comment]
/approve

Note we've got 0.16.3 coming out today as well - but I doubt it'll impact these images (famous last words)

**Comment by bobcatfish** [comment]
Thanks for doing this @vinamra28 !

> I doubt it'll impact these images (famous last words)

just realized this includes the version installed by the tests as well, I'll make a PR to update these as well

**Comment by bobcatfish** [comment]
Thinking about this a bit more, I'm not sure we want to bump these in the future without bumping the Task version as well - maybe can discuss in https://github.com/tektoncd/pipeline/pull/3258

**Pull request merged**
