### PR TITLE
Add Daniel Haus to RHACS task owners

### PR DESCRIPTION
**Pull request by dlbewley**
# Changes

Add Daniel Haus to RHACS Tasks Owners

### CODE REVIEW

**Comment by vinamra28** [comment]
@dlbewley, can you please raise a PR in tektoncd/community and get yourself added into the community?

**Comment by dhaus67** [comment]
@vinamra28 [the PR has been raised & merged](https://github.com/tektoncd/community/pull/1145); is there anything else we're missing?

**Comment by vinamra28** [comment]
@dhaus67, you might have received the github invite to join the org. Can you please check your email inbox?

**Comment by dhaus67** [comment]
> @dhaus67, you might have received the github invite to join the org. Can you please check your email inbox?

I've checked but haven't received anything yet :/ Any chance you can trigger a re-send?

**Comment by dhaus67** [comment]
@vinamra28 FWIW I received the invite now and already accepted it, thanks for resolving this!

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
