### PR TITLE
Fix e2e: Test remaining tasks after parellelization

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

Currently no of parallel tasks running at a time are 5
but in case the last set of tasks doesn't count upto 5
then handling that case over here.

/hold

Signed-off-by: vinamra28 <vinjain@redhat.com>
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by chmouel** [comment]
👍 thanks for fixing this,

I'l let you finish the testing and will add my lgtm

**Comment by vinamra28** [comment]
Tested successfully in https://github.com/tektoncd/catalog/commit/46d7102900a6af06fec00f40ec7c87d3f45b47ad and link to logs are [here](https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_catalog/598/pull-tekton-catalog-integration-tests/1336608534938259458/?log#log)
/hold cancel

**Comment by vinamra28** [comment]
ready for review :slightly_smiling_face: 
/cc @chmouel @vdemeester

**Review by sbwsg — APPROVED** [review]

**Pull request merged**
