### PR TITLE
feature: add gitignore

### PR DESCRIPTION
**Pull request by shaowenchen**
Signed-off-by: shaowenchen <mail@chenshaowen.com>

# Changes

Ignore some unnecessary files from the repository.

### CODE REVIEW

**Comment by chmouel** [comment]
Thanks for your contribution but it's probably no the best way to do this. 

The editor configs are better addressed with a global exclusion in your ~/.gitconfig. At the same time you won't have to send a PR for a gitignore on every projects you work on and hasn't one :) 

See this article about the reasoning behind it and how to do it : 

https://julien.danjou.info/properly-managing-your-gitignore/

/hold

**Comment by shaowenchen** [comment]
> Thanks for your contribution but it's probably no the best way to do this.
> 
> The editor configs are better addressed with a global exclusion in your ~/.gitconfig. At the same time you won't have to send a PR for a gitignore on every projects you work on and hasn't one :)
> 
> See this article about the reasoning behind it and how to do it :
> 
> https://julien.danjou.info/properly-managing-your-gitignore/
> 
> /hold

The majority of repositories will have a .gitignore file, including https://github.com/tektoncd.

This is just for developers and not every developer knows to configure a global .gitinore file.

**Comment by chmouel** [comment]
Yep but where does it stop, if the user starts to use a new editor, is he or she going to add everything to the .gitignore every time because they didn't know how git exclude works ? Should we assume every one is using the same editors like vscode/golang, probably not, isnt it ? I would rather help and educate the user  on how to do configure global gitignore properly

**Comment by shaowenchen** [comment]
OK.

**Pull request closed without merging**
