### PR TITLE
Adding pre_script parameter.

### PR DESCRIPTION
**Pull request by peterbosalliandercom**
# Changes

We need to install binaries before the go test can be run. In our case we need kubebuilder before we can run go tests in conjuction with operator-sdk which needs kubernetes client, etcd etc. 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by chmouel** [comment]
usually in tekton pipelines world you would have another task before this golang task with a shared workspace between the two that does that and do "pre" stuff? this is not working for you ?

**Comment by peterbosalliandercom** [comment]
> olang task

Before we run the golang task we need kubebuilder for that. With the pre-script way we can install and configure the kubebuilder. I expect that more users will need this pre-scripting in order to bootstrap the environment before they run the actual go test. It would be great if instead of the pre-script it would be possible to have a sort of boolean that includes the kubebuilder automatically but i think that is not really easy to do. Do you have an idea how to run these scripts using existing tekton taks? As an example we are using this pre-script right now. Do you have any other way to do this?
` 
 - name: PRE_SCRIPT
      description: Running pre_script before main script is executed
      type: string
      default: |
        export K8S_VERSION=1.21.2
        curl -sSLo envtest-bins.tar.gz "https://go.kubebuilder.io/test-tools/${K8S_VERSION}/$(go env GOOS)/$(go env GOARCH)"
        mkdir /usr/local/kubebuilder
        tar -C /usr/local/kubebuilder --strip-components=1 -zvxf envtest-bins.tar.gz`

**Comment by chmouel** [comment]
@peterbosalliandercom you would have another task just before the golang task that does in its script the shell snippet you have in there and this would be add subsequently to the golang task (assuming you have added runAfter: this pre task)

**Comment by peterbosalliandercom** [comment]
> @peterbosalliandercom you would have another task just before the golang task that does in its script the shell snippet you have in there and this would be add subsequently to the golang task (assuming you have added runAfter: this pre task)

Is there a task available in the catalog for that? If so that would be great.

**Comment by chmouel** [comment]
> Is there a task available in the catalog for that? If so that would be great.

that would just be inline task using a shell image  with the script directive 

ie:

```yaml
      - name: pretask
        runAfter:
          - git-clone-task
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro #or alpine or others
              workingDir: $(workspaces.source.path)
              script: |
				# Your script that would do a kubebuilder
                exit 0
   - name: golang-test
     taskRef: golang
     etc.... 
```

i think that should work

**Pull request closed without merging**
