### PR TITLE
Update multi-arched trivy image

### PR DESCRIPTION
**Pull request by varsha-aaynure**
# Changes
Updated default value for TRIVY_IMAGE to multi-arch value

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations][authoring]
- [ ] Includes [docs][docs] (if user facing)
- [ ] Includes [tests][tests] (for new tasks or changed functionality)
  - See the [end-to-end testing documentation][e2e] for guidance and CI details.
- [x] Meets the [Tekton contributor standards][contributor] (including functionality, content, code)
- [x] Commit messages follow [commit message best practices][commit]
- [ ] Has a kind label. You can add one by adding a comment on this PR that
  contains `/kind <type>`. Valid types are bug, cleanup, design, documentation,
  feature, flake, misc, question, tep
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```
          spec:
            description: >-
              Updated Trivy-scanner Task (supporting ppc64le arch)
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md) for more details._

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]: https://github.com/tektoncd/catalog/issues/413
[authoring]: https://github.com/tektoncd/catalog/blob/main/recommendations.md
[docs]: https://github.com/tektoncd/community/blob/master/standards.md#docs
[tests]: https://github.com/tektoncd/community/blob/master/standards.md#tests
[e2e]: https://github.com/tektoncd/catalog/blob/main/CONTRIBUTING.md#end-to-end-testing
[contributor]: https://github.com/tektoncd/community/blob/main/standards.md
[commit]: https://github.com/tektoncd/community/blob/master/standards.md#commit-messages

### CODE REVIEW

**Review by afrittoli — COMMENTED** [review]
Thanks @varsha-aaynure for this PR.
It looks like the catlin linter added some extra requirements since this was last modified, so you may need to fix the following issue for CI to pass:

```
[lint-catalog : lint-catalog] ERROR: /usr/bin/shellcheck, [-s sh] failed:
[lint-catalog : lint-catalog] 
[lint-catalog : lint-catalog] In trivy-scanner-trivy-scan line 6:
[lint-catalog : lint-catalog]     trivy --cache-dir $TRIVY_TEMP_DIR image --download-db-only
[lint-catalog : lint-catalog]                       ^-------------^ SC2086: Double quote to prevent globbing and word splitting.
```

Otherwise the change looks good to me!
/lgtm

**Comment by jkandasa** [comment]
@afrittoli looks like the current test failure with cluster creation code? I see this issue in other PRs too.

```
2023/07/17 10:36:57 process.go:155: Step 'gcloud beta container clusters create --quiet --enable-autoscaling --min-nodes=1 --max-nodes=3 --scopes=cloud-platform --no-issue-client-certificate --project=tekton-prow-4 --region=us-central1 --machine-type=n1-standard-4 --image-type=cos_containerd --num-nodes=1 --network=tcatalog-e2e-net1680887605475938304 --cluster-version=1.26.5-gke.1200 tcatalog-e2e-cls1680887605475938304' finished in 4m58.73928602s
2023/07/17 10:36:57 process.go:153: Running: ./cluster/kubectl.sh --match-server-version=false version
error: The gcp auth plugin has been removed.
Please use the "gke-gcloud-auth-plugin" kubectl/client-go credential plugin instead.
```

**Comment by afrittoli** [comment]
> @afrittoli looks like the current test failure with cluster creation code? I see this issue in other PRs too.
> 
> ```
> 2023/07/17 10:36:57 process.go:155: Step 'gcloud beta container clusters create --quiet --enable-autoscaling --min-nodes=1 --max-nodes=3 --scopes=cloud-platform --no-issue-client-certificate --project=tekton-prow-4 --region=us-central1 --machine-type=n1-standard-4 --image-type=cos_containerd --num-nodes=1 --network=tcatalog-e2e-net1680887605475938304 --cluster-version=1.26.5-gke.1200 tcatalog-e2e-cls1680887605475938304' finished in 4m58.73928602s
> 2023/07/17 10:36:57 process.go:153: Running: ./cluster/kubectl.sh --match-server-version=false version
> error: The gcp auth plugin has been removed.
> Please use the "gke-gcloud-auth-plugin" kubectl/client-go credential plugin instead.
> ```

Thanks for pointing this out, this is not preventing the test cluster from starting though, the actual issue is down below in the logs 

```
--- Container Logs
2023/07/17 12:15:48 Error executing command: fork/exec /tekton/scripts/script-0-zznmv: exec format error
```

**Review by afrittoli — COMMENTED** [review]
Thanks for this! 
/lgtm

**Comment by varsha-aaynure** [comment]
for this will raise new PR with one commit.

**Pull request closed without merging**
