### PR TITLE
fix argocd sync and wait task

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

Logging in from one container and having sync and wait run in the separate containers does not work. Authenticate once and reuse the connection across the containers in a pod is not supported. Sync and wait fails with the authentication error. Either we login at each step or collapse sync and wait along with the login step. Or we could authenticate once and
find a way to how to reuse the same connection across the containers.

For now, combining everything into a single step.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Review by chmouel — COMMENTED** [review]
/lgtm

Looking Good! 🤙🏽 thanks!

and FYI I am not sure how those images are made but if you had #!/bin/bash instead of #!/bin/sh available in the image you could easily avoid those quote issue with double brackets (ie https://stackoverflow.com/a/669486/145125)

**Review by vinamra28 — COMMENTED** [review]
I wonder if we should deprecate 0.1 version of this task and add this as version 0.2 since this is a major change in this task ?
/cc @tektoncd/catalog-maintainers

**Comment by chmouel** [comment]
If i understand correctly it's a fix of something that wasn't working at all, so i guess bumping does not change much, but let's see what @pritidesai thinks about this!

**Comment by pritidesai** [comment]
> If i understand correctly it's a fix of something that wasn't working at all, so i guess bumping does not change much, but let's see what @pritidesai thinks about this!

Right, the current task definition is not working at all, this PR is just the fix so let's not bump the version right now.
Ideally I would like to add an automation `tests/` as well, we can bump the version with the `tests/` later.

**Comment by vinamra28** [comment]
> > If i understand correctly it's a fix of something that wasn't working at all, so i guess bumping does not change much, but let's see what @pritidesai thinks about this!
> 
> Right, the current task definition is not working at all, this PR is just the fix so let's not bump the version right now.
> Ideally I would like to add an automation `tests/` as well, we can bump the version with the `tests/` later.

Makes sense. Will merge this for now then
/approve

**Pull request merged**
