### PR TITLE
use sed to add sidecar and remove python

### PR DESCRIPTION
**Pull request by 06kellyjac**
# Changes

python and pyyaml are currently required to inject an optional sidecar for a registry.

This PR uses sed to inject that sidecar and removes the need for python
Benefits include reducing attack surface and the requirement for 2 extra dependencies

Also I set `require_command` to check for the kubectl command

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by 06kellyjac** [comment]
Friendly bump :slightly_smiling_face:

**Comment by chmouel** [comment]
if it works then that's perfect! 

best solution would be to move away from sidecar! and just start the reg service before running the tests...

https://github.com/tektoncd/catalog/issues/561

/lgtm

**Comment by 06kellyjac** [comment]
Ah ok, might look at #561 at some point

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
