### PR TITLE
v0.2 for orka-full task

### PR DESCRIPTION
**Pull request by jkomoda**
# Changes

Added version `0.2` for `orka-full` task

* Compatibility changes to make the pipelines also work properly when using Tekton v0.34.1
* Added additional task parameters for feature parity with Orka v2.1.0:
  * `system-serial`: Assign an owned macOS system serial number to the VM (on Intel nodes only).
  * `gpu-passthrough`: Enables or disables GPU passthrough for the VM (on Intel nodes only).
  * `tag`: When specified, the VM is preferred to be deployed to a node marked with this tag.
  * `tag-required`: VM is required to be deployed to a node marked with tag specified above.
  * `scheduler`: When set to 'most-allocated', the deployed VM will be scheduled to nodes having most of their resources allocated.
* Modified build-audiokit-pipeline example to use a different open-source iOS project (Calcupad) for compatibility reasons
* Changes in scripts to dynamically add additional parameters to VM config/deploy request when they are passed in pipelines

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by jkomoda** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/8049964/183500906/1014/#/?version=2)
> 
> * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/8049964/183500906/1014/#/?version=2) - login: @jkomoda / name: Jason Komoda . The commit ([8c13815](https://github.com/tektoncd/catalog/commit/8c13815ce4e12036a2b3322987684b1cfd00d9ae), [0a8a968](https://github.com/tektoncd/catalog/commit/0a8a9681e9dfbc27b69c324dce551c96d9a39a70)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/8049964/183500906/1014/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

Currently waiting on my CLA request to be approved

**Review by vinamra28 — APPROVED** [review]
/lgtm

**Pull request merged**
