### PR TITLE
Fix catalog test for ppc64le

### PR DESCRIPTION
**Pull request by Sachin-Itagi**
# Changes

Replaces the GRADLE_IMAGE parameter for gradle/0.4 to the multi-arch alternative. Currently the image is x86 only.

Added an Extra MAVEN_IMAGE parameter which is missing for the maven-0-3 test via linux-ppc64le.sh script.

Added a patch command to enable Step Actions on the cluster. This is needed for stepaction test.

Added a patch command to disable Affinity Assistant  on the cluster. This allow binding of two PVCs at the same time and is needed by the maven-0-3 test.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations][authoring]
- [ ] Includes [docs][docs] (if user facing)
- [ ] Includes [tests][tests] (for new tasks or changed functionality)
  - See the [end-to-end testing documentation][e2e] for guidance and CI details.
- [x] Meets the [Tekton contributor standards][contributor] (including functionality, content, code)
- [x] Commit messages follow [commit message best practices][commit]
- [x] Has a kind label. You can add one by adding a comment on this PR that
  contains `/kind <type>`. Valid types are bug, cleanup, design, documentation,
  feature, flake, misc, question, tep
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md) for more details._

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]: https://github.com/tektoncd/catalog/issues/413
[authoring]: https://github.com/tektoncd/catalog/blob/main/recommendations.md
[docs]: https://github.com/tektoncd/community/blob/master/standards.md#docs
[tests]: https://github.com/tektoncd/community/blob/master/standards.md#tests
[e2e]: https://github.com/tektoncd/catalog/blob/main/CONTRIBUTING.md#end-to-end-testing
[contributor]: https://github.com/tektoncd/community/blob/main/standards.md
[commit]: https://github.com/tektoncd/community/blob/master/standards.md#commit-messages

### CODE REVIEW

**Comment by Sachin-Itagi** [comment]
@vdemeester @bobcatfish Can you please review this PR which fixes the catalog test for Power.

**Comment by valen-mascarenhas14** [comment]
@afrittoli  could you please review this PR ?

**Review by vinamra28 — APPROVED** [review]
/lgtm
/ok-to-test

**Comment by Sachin-Itagi** [comment]
@vinamra28 @vdemeester Any suggestions on resolving the failure observed during the pull-tekton-catalog-integration-tests Job. The changes that have been made don't seem to be the cause of this issue and It doesn't seem to be a flaky issue as well.

It seems to be an issue with PIP.
```Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) - skipping```

Any help to resolve this issue and merge the PR would be appreciated. Thanks.

**Comment by vinamra28** [comment]
@Sachin-Itagi, this task should get fixed in https://github.com/tektoncd/catalog/pull/1266

**Pull request merged**
