### PR TITLE
Change test repo to cli from pipeline in golang-test task

### PR DESCRIPTION
**Pull request by piyush-garg**
This will change the golang-test task tests to use cli repo for
unit test rather than pipeline repo as the test is failing there

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by chmouel** [comment]
Are you sure the test is failing there? The tests are CIed on any change on pipeline, isnt there another issue somewhere we are workarounding?

**Comment by piyush-garg** [comment]
> Are you sure the test is failing there? The tests are CIed on any change on pipeline, isnt there another issue somewhere we are workarounding?

The issue is with running on a non-root environment I guess

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Review by vdemeester — APPROVED** [review]

**Comment by vdemeester** [comment]
(EasyCLA was stuck, closed/reopen to force the check 😅 )

**Pull request merged**
