### PR TITLE
Add a helper script to run a task test directly on your local cluster

### PR DESCRIPTION
**Pull request by chmouel**
# Changes

This script will allow the developer to test a task directly withouth having to
send it to the CI and wait that all tasks runs to test it.

Usage is : 

```./test/run-test.sh git-clone 0.1```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

**Comment by bobcatfish** [comment]
@chmouel i've nearly got a TEP ready to go at https://github.com/tektoncd/community/pull/170 about trying to move from a more bash script centric approach here to more Task + Pipeline based

**Comment by chmouel** [comment]
@bobcatfish we can perhaps remove this when the TEP would be implemented? in the meantime it will be much more useful for task developers to be able to run those tests locally (ie: not on CI) first before sending to CI, what do you think?

**Comment by vdemeester** [comment]
@bobcatfish nice :upside_down_face: That said, I still it's still very useful to be able to quickly run a catalog test locally (aka I am on my laptop, running `kind` or `minikube`) for the contributors — and I am not sure the TEP linked does help on this (I don't see it as a goal after a quick look). So I tend to agree with @chmouel :angel:

**Comment by vinamra28** [comment]
@chmouel thanks for adding this task. This would really be very helpful while adding a new task to the catalog. I tried running this against existing maven task as
`./test/run-script.sh maven 0.1` and geting the following logs
```
+ kubectl -n maven-0-1 create -f /tmp/.mm.M9Qi6x
pipeline.tekton.dev/maven-test-pipeline created
pipelinerun.tekton.dev/maven-test-pipeline-run created
+ local cnt=0
+ true
+ [[ 0 == 60 ]]
++ kubectl get -n maven-0-1 pipelinerun '--output=jsonpath={.items[*].status.conditions[*].status}'
+ all_status=
++ kubectl get -n maven-0-1 pipelinerun '--output=jsonpath={.items[*].status.conditions[*].reason}'
+ reason=Running
+ [[ -z '' ]]
+ [[ -z Running ]]
+ [[ -z '' ]]
+ echo -n 'Could not find a created taskrun or pipelinerun in maven-0-1'
Could not find a created taskrun or pipelinerun in maven-0-1+ breakit=True
+ [[ True == True ]]
+ echo -n 'SUCCESS: maven pipelinerun has successfully executed'
SUCCESS: maven pipelinerun has successfully executed+ break
+ kubectl delete ns maven-0-1
namespace "maven-0-1" deleted
+ clean
+ rm -f /tmp/.mm.M9Qi6x
```
is this expected? :thinking:

**Comment by chmouel** [comment]
@vinamra28 yeah i think that conditional can be improved since there is no reason yet but the loop after catches it properly.


fyi what is run here is what we run in CI since it uses the same mechanism.

**Comment by piyush-garg** [comment]
This looks very helpful while doing development.

**Pull request merged**
