### PR TITLE
git-clone: 0.8 -> 0.9, bump git-init image + fix tests

### PR DESCRIPTION
**Pull request by jhonis**
# Changes

Note: this is supposed to be similar to the PR https://github.com/tektoncd/catalog/pull/1076. I just didn't want to change its commit structure as the CONTRIBUTING.md suggests us to push one commit with the version copy first.
- Bump up version of `git-init` image to `0.40.2`
- Fix tests by adding the `safe.directory` config to git
- Change the HOME directory so the ssh authentication works fine

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Follows the [authoring recommendations][authoring]
- [X] Includes [docs][docs] (if user facing)
- [X] Includes [tests][tests] (for new tasks or changed functionality)
  - See the [end-to-end testing documentation][e2e] for guidance and CI details.
- [X] Meets the [Tekton contributor standards][contributor] (including functionality, content, code)
- [X] Commit messages follow [commit message best practices][commit]
- [X] Has a kind label. You can add one by adding a comment on this PR that
  contains `/kind <type>`. Valid types are bug, cleanup, design, documentation,
  feature, flake, misc, question, tep
- [X] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [X] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [X] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [X] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [X] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [X] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md) for more details._

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]: https://github.com/tektoncd/catalog/issues/413
[authoring]: https://github.com/tektoncd/catalog/blob/main/recommendations.md
[docs]: https://github.com/tektoncd/community/blob/master/standards.md#docs
[tests]: https://github.com/tektoncd/community/blob/master/standards.md#tests
[e2e]: https://github.com/tektoncd/catalog/blob/main/CONTRIBUTING.md#end-to-end-testing
[contributor]: https://github.com/tektoncd/community/blob/main/standards.md
[commit]: https://github.com/tektoncd/community/blob/master/standards.md#commit-messages

### CODE REVIEW

**Comment by vdemeester** [comment]
```
task/git-clone/0.9/git-clone.yaml
  1[76](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_catalog/1092/pull-tekton-catalog-build-tests/1582365581464571904#1:build-log.txt%3A76):1     error    trailing spaces  (trailing-spaces)
task/git-clone/0.9/samples/git-clone-checking-out-a-commit.yaml
  115:26    warning  too few spaces before comment  (comments)
```
@jhonis 🙏🏼 

/approve

**Comment by jhonis** [comment]
Hey folks, could you please add the LGTM label to this PR so it gets merged? 😊 
cc: @vdemeester @chmouel

**Comment by chmouel** [comment]
ah damn you right, i always forget about it thanks @vinamra28 will try to make sure for next time...

**Pull request merged**
