### PR TITLE
Add helm Task

### PR DESCRIPTION
**Pull request by fhopfensperger**
# Changes

This `Task` can be used to install/upgrade a helm chart (located in a git repo) into a Kubernetes/OpenShift Cluster.

Signed-off-by: Florian Hopfensperger <florian.hopfensperger@de.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules. (Except line length)

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by fhopfensperger** [comment]
@sbwsg Sorry, I'm not sure what the next steps are. This is my first PR for tekton.

**Comment by vdemeester** [comment]
@fhopfensperger the invalid-owners-file means you need to be part of the organization — you can create a PR on `tektoncd/community` to add yourself (see https://github.com/tektoncd/community/pull/106 for inspiration, you can say you mean to own a task in the catalog :wink: )

/cc @eddycharly @chmouel

**Comment by fhopfensperger** [comment]
@vdemeester Thank you for the information 🙏 
I just opened a pull request https://github.com/tektoncd/community/pull/116
Hopefully, I did everything right. 🙈

**Comment by fhopfensperger** [comment]
/retest
hopefully solves the OWNERS exception

**Comment by fhopfensperger** [comment]
hopefully solves the OWNERS exception

/verify-owners

**Comment by fhopfensperger** [comment]
@vdemeester Sorry, I'm not sure if `/verify-owners` is working properly or if I'm doing something wrong? Could you help me, please?

**Pull request merged**
