### PR TITLE
Run Sonar-scanner as root

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

This will fix the issue of task not working on OpenShift as it needs root access and by default on OpenShift pod run as nonroot.

Signed-off-by: vinamra28 <vinjain@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [X] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by chmouel** [comment]
Let's wait until https://jira.sonarsource.com/browse/MMF-2003 get merged then and we won't need this pr ?

**Comment by vinamra28** [comment]
> Let's wait until https://jira.sonarsource.com/browse/MMF-2003 get merged then and we won't need this pr ?

yeah true....shall I close this PR now?

**Comment by chmouel** [comment]
yes please, i think it would be best..

**Comment by vinamra28** [comment]
closing this PR as the upstream will fix this issue in https://jira.sonarsource.com/browse/MMF-2003

**Pull request closed without merging**
