### PR TITLE
Update catalog e2e test runner to use Pipelines version 0.23.0

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes

Pipelines just released v0.23.0.

This commit updates the e2e test runner to use the new version
of Pipelines when testing catalog entries.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

**Comment by sbwsg** [comment]
```
Unable to connect to the server: http2: client connection lost
```


/test pull-tekton-catalog-integration-tests

**Review by vdemeester — APPROVED** [review]
/meow

**Comment by sbwsg** [comment]
`Unable to connect to the server: net/http: TLS handshake timeout`

Will investigate further if a third run doesn't succeed but I think this is just network weather or maybe pods being preempted?

/test pull-tekton-catalog-integration-tests

**Pull request merged**
