### PR TITLE
Add version 0.2 to jib-maven task

### PR DESCRIPTION
**Pull request by barthy1**
# Changes
    - Add parameter for the maven image
    - Replace usage of PipelineResource to image name as param and image digest as
    results

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by chmouel** [comment]
/lgtm

I am not sure what would be the policy if we bump task every time for new params but either way i am good!

**Review by vinamra28 — COMMENTED** [review]
hi @barthy1, since a new parameter is being added can we just bump the version of the task to avoid any user experience break?

**Comment by vinamra28** [comment]
> /lgtm
> 
> I am not sure what would be the policy if we bump task every time for new params but either way i am good!

Hi @chmouel, yes we need to bump the version as it's documented in [TEP-0003 Versioning Resources](https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md#versioning-resources) although I don't see any breaking change :sweat_smile:

**Comment by chmouel** [comment]
@vinamra28 I think @bobcatfish is as well in favor to always bump change, I am not sure if @piyush-garg and @vdemeester have an opinion on it, but we may just do that and follow to always make PR bumping changes on params additions, what do you think?

**Comment by barthy1** [comment]
@chmouel @vinamra28 I don't have specific preferences here and can bump the version of the task. 
It just looks overcommitment to me in the current case, but tep is tep :) Let me know, if it's already final recommendation.

Sorry, that I didn't review [TEP-0003 Versioning Resources](https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md#versioning-resources) before. Do I understand correct, that any image update also should bump task version?

**Comment by vinamra28** [comment]
> Sorry, that I didn't review [TEP-0003 Versioning Resources](https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md#versioning-resources) before. Do I understand correct, that any image update also should bump task version?

In case of image we only bump the task version if there is breaking change in image otherwise we don't bump the task instead updates the existing.

**Comment by vinamra28** [comment]
> @vinamra28 I think @bobcatfish is as well in favor to always bump task version on changes, I am not sure if @piyush-garg and @vdemeester have an opinion on it, but we may just do that and follow to always make PR bumping changes on params additions, what do you think?

Yeah we can bump the task for now as per TEP.

**Comment by vdemeester** [comment]
Right, according to the proposal, adding a parameter should be done in a new version. We could refine this and say it has to be in a new version **if the parameter has no default value**, but as of today, I think we should bump yes.

**Comment by barthy1** [comment]
Thanks to all reviewers. I've added to jib-maven 0.2 version.

**Review by Divyansh42 — APPROVED** [review]
/lgtm

Thanks :+1:

**Comment by chmouel** [comment]
/lgtm

thank you @barthy1

**Review by vinamra28 — COMMENTED** [review]
The PR looks good :+1: 
Can you address a part of the issue #584 ie instead of using `PipelineResource` using `params`+`results` for the image? I am asking this because since you are bumping a new version then probably we can get part of this issue also addressed. Please do let me know your thoughts on it.
/lgtm

**Comment by barthy1** [comment]
@vinamra28 sure, will do.
I will follow the same pattern as kaniko and buildah tasks use.

**Comment by vinamra28** [comment]
> @vinamra28 sure, will do.
> I will follow the same pattern as kaniko and buildah tasks use.

Thanks @barthy1 :+1:

**Comment by barthy1** [comment]
@vinamra28 Hey, requested changes are done. Please, review!

**Review by vinamra28 — COMMENTED** [review]
Thanks :+1: 
/approve
/meow

**Review by Divyansh42 — COMMENTED** [review]
/lgtm

**Pull request merged**
