### PR TITLE
Fixes #112

### LINKED ISSUE #112: buildah: Need input parameter for build context
# Expected Behavior

Suppose we have a repository like this:

`./foo/Dockerfile`
`./foo/bar`
`./foo/bar/Makefile`

where `./foo/Dockerfile` has:

```
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install make
COPY . /app
RUN make -f /app/bar/Makefile
```

In order to build this properly, there should be an input parameter available to specify the build context as `./foo`.

# Actual Behavior

However, the build command is currently:

```
    command: ['buildah', 'bud', '--tls-verify=$(inputs.params.TLSVERIFY)', '--layers', '-f', '$(inputs.params.DOCKERFILE)', '-t', '$(outputs.resources.image.url)', '.']
```

There is currently no way to specify the build context in a `TaskRun`.

# Steps to Reproduce the Problem

# Additional Info

### PR DESCRIPTION
**Pull request by NicolasRouquette**
# Changes

Added & documented a new input parameter, `CONTEXT`, for the path to the Dockerfile context directory.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by NicolasRouquette** [comment]
@googlebot I signed it!

**Comment by chmouel** [comment]
/ok-to-test

It would be nice if the commit message follow git best practice (as linked in the issue template)

**Comment by NicolasRouquette** [comment]
FYI: There are different ways to solve the issue.

1) As proposed in the PR, which retains the original specification of the `DOCKERFILE` input param:

```
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: Path to the Dockerfile context directory.
      default: .
```

Then, the command becomes:

```
 workingDir: /workspace/source
 command: ['buildah', 'bud', '--tls-verify=$(inputs.params.TLSVERIFY)', '--layers', '-f', '$(inputs.params.DOCKERFILE)', '-t', '$(outputs.resources.image.url)', '$(inputs.params.CONTEXT)']
```

2) A variant with a slight change to the meaning of the `DOCKERFILE` input param:


```
    - name: DOCKERFILE
      description: Name of the dockerfile in the CONTEXT directory
      default: Dockerfile
    - name: CONTEXT
      description: Path to the context directory for the DOCKERFILE
      default: .
```

Then, the command becomes:

```
 workingDir: /workspace/source/$(inputs.param.CONTEXT)
 command: ['buildah', 'bud', '--tls-verify=$(inputs.params.TLSVERIFY)', '--layers', '-f', '$(inputs.params.DOCKERFILE)', '-t', '$(outputs.resources.image.url)', '.']
```

There are pros/cons to either approach.

1):
pros: maintains compatibility with the current definition of the `DOCKERFILE` parameter.
cons: I've had problems with this approach; specifically, it seems that buildah first changes the context directory and then attempts to resolve the dockerfile from the `-f` argument. So, this results in error.

2)
pros: this works in our cluster; it is unclear to me how to write a unit test for the project though.
cons: it is an incompatible change w.r.t. the current definition of the `DOCKEFILE` parameter.

**Comment by piyush-garg** [comment]
Seems the same PR #171 has been merged

**Comment by vdemeester** [comment]
/close
Thanks @NicolasRouquette

**Pull request closed without merging**
