### PR TITLE
Improve Readme.md

### PR DESCRIPTION
**Pull request by ishani2412**
# Changes
PR to improve the Readme.md migrating the install task URL from
master to v1beta1

Signed-off-by: ishani2412 <ishani.1613039@kiet.edu>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by bobcatfish** [comment]
Hey @ishani2412 ! Thanks for doing this - I think we're on the verge of switching back to master as our main branch instead of v1beta1, however I'm not sure what the timeframe is so maybe it would make sense to merge this for now and then we can revert it once we switch back to master 🤔

**Comment by vinamra28** [comment]
Hi @bobcatfish it would be great doing this as of now since users using the tasks from catalog would sometimes be using the older version of the task unknowingly what I think :thinking:

**Comment by ishani2412** [comment]
> Hey @ishani2412 ! Thanks for doing this - I think we're on the verge of switching back to master as our main branch instead of v1beta1, however I'm not sure what the timeframe is so maybe it would make sense to merge this for now and then we can revert it once we switch back to master 🤔

Hi @bobcatfish do I need to make any changes in order to get it merged?

**Comment by ishani2412** [comment]
@ImJasonH @sbwsg could you please review the PR and merge if it looks good to you :slightly_smiling_face:

**Comment by sbwsg** [comment]
@vdemeester is planning to sync `master` against `v1beta1` on June 15th so there's still a couple of weeks to go.  Approved this to point people in the right direction until then.

**Pull request merged**
