### PR TITLE
add OpenShift ImageStream Tekton example

### PR DESCRIPTION
**Pull request by gabemontero**
# Changes

Submitting some example usage of OpenShift ImageStreams with Tekton

/assign @vdemeester 

@siamaksade @bparees @sbose78 @adambkaplan FYI

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [/] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [/] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [/] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by gabemontero** [comment]
> The following users are mentioned in OWNERS file(s) but are not members of the tektoncd org.
> 
>     * gabemontero
>       
>       * openshift-image-stream/OWNERS
>       * openshift-image-stream/OWNERS

eeesh ... though I was a member as part of the usual signup stuff ... 

@vdemeester any suggestions on how to get added?

**Comment by vdemeester** [comment]
> > The following users are mentioned in OWNERS file(s) but are not members of the tektoncd org.
> > ```
> > * gabemontero
> >   
> >   * openshift-image-stream/OWNERS
> >   * openshift-image-stream/OWNERS
> > ```
> 
> eeesh ... though I was a member as part of the usual signup stuff ...
> 
> @vdemeester any suggestions on how to get added?

You need to be part of the organization to be an `OWNER`, it doesn't have anything to do with the CLA :wink:. A PR like [this one](https://github.com/tektoncd/community/pull/76) should suffice.

On this, maybe we should add the content of this in the [`openshift-client`](https://github.com/tektoncd/catalog/tree/master/openshift-client) as an additional task ? (or maybe not :stuck_out_tongue_closed_eyes:). We will also need to have, at some point, a way to mark `Task`s as "limited to …" (here Limited to OpenShift).

**Comment by gabemontero** [comment]
> > > The following users are mentioned in OWNERS file(s) but are not members of the tektoncd org.
> > > ```
> > > * gabemontero
> > >   
> > >   * openshift-image-stream/OWNERS
> > >   * openshift-image-stream/OWNERS
> > > ```
> > 
> > 
> > eeesh ... though I was a member as part of the usual signup stuff ...
> > @vdemeester any suggestions on how to get added?
> 
> You need to be part of the organization to be an `OWNER`, it doesn't have anything to do with the CLA wink. A PR like [this one](https://github.com/tektoncd/community/pull/76) should suffice.

Submitted https://github.com/tektoncd/community/pull/83 ... thanks 
> 
> On this, maybe we should add the content of this in the [`openshift-client`](https://github.com/tektoncd/catalog/tree/master/openshift-client) as an additional task ? (or maybe not stuck_out_tongue_closed_eyes). We will also need to have, at some point, a way to mark `Task`s as "limited to …" (here Limited to OpenShift).

Yeah while there is some `oc` usage there, I really think we want to highlight `ImageStream` and as such have a separate directory.  Also, it might overly clutter what you all already have for openshift-client.

Also note, I'm considering changing the imagestream yaml file to include the changes that stem from running `oc set image-lookup` as well as add the needed annotation to the  task yaml.  I went back and forth on if it would be more instructive to have the user  take those steps to enable vs. referencing in the yaml what was needed.  But certainly chime in @vdemeester if you have an opinion.

thanks again

**Comment by siamaksade** [comment]
@gabemontero @vdemeester would it make sense to publish this task as an example under the [buildah](https://github.com/tektoncd/catalog/tree/master/buildah) task? 

Alternatively add it as a new task called `buildah-imagestream` and update the description so that it reflects that it's for using `buildah` to build an image and push to an imagestream on OpenShift.

**Comment by gabemontero** [comment]
> @gabemontero @vdemeester would it make sense to publish this task as an example under the [buildah](https://github.com/tektoncd/catalog/tree/master/buildah) task?
> 
> Alternatively add it as a new task called `buildah-imagestream` and update the description so that it reflects that it's for using `buildah` to build an image and push to an imagestream on OpenShift.

I used `buildah` @siamaksade but that certainly is not a requirement for demonstrating imagestreams.  I could have used one of the other well known tools.  I think I have the similar thought that we would lose the 'imagestream visibility' by putting it under the existing openshift client or buildah folders.

Existing imagestream users *might* not think to look under those dirs when researching.

Think about it ... but I'll ultimately defer to you or @vdemeester if either of you feel strongly about it.

**Comment by gabemontero** [comment]
I've updated the PR to include the annotation in the Task and simply note its presence in the README

**Comment by gabemontero** [comment]
Ahh ... the integration tests do not like my rolebinding file with the namespace commented out.
And since they are doing kubectl apply's,  it will not like my imagestream  yaml file as well

I'll remove those and just explain how to achieve them with `oc`

**Comment by gabemontero** [comment]
ok ... green tests at least ... but after talking with @siamaksade some more I'm going to close this out and move it downstream

**Pull request closed without merging**
