### PR TITLE
Cherry-pick some fixes from master

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Some pullrequest were merged in master while we were working on `v1beta1`. This cherry-pick those that could :angel: 

/cc @sbwsg @chmouel 

It'll need a manual `cla` check :stuck_out_tongue_closed_eyes: 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Comment by sbwsg** [comment]
> (Googler, please make sure the reason for overriding the CLA status is clearly documented in these comments.)

These commits are from master and have already passed through the CLA process once.

**Comment by chmouel** [comment]
/lgtm
/approve

Thanks 👍🏼🔥

**Pull request merged**
