### PR TITLE
Add DOCKER_CONFIG env to avoid authorization issue

### PR DESCRIPTION
**Pull request by savitaashture**
# Changes

Added `DOCKER_CONFIG` env in order to avoid authorization error.
The credentials are looked at `/tekton/home` or `/tekton/creds` based on pipeline version so to make it generic used `$(credentials.path)`.

/cc @vdemeester @sbwsg 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Orgainization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by ppitonak** [comment]
```
[build : build-and-push] [INFO] Using credentials from Docker config (/tekton/home/.docker/config.json) for image-registry.openshift-image-registry.svc:5000/catalog-tests/console-java-simple
[build : build-and-push] [WARNING] Cannot verify server at https://image-registry.openshift-image-registry.svc:5000/v2/. Attempting again with no TLS verification.
[build : build-and-push] [WARNING] Cannot verify server at https://image-registry.openshift-image-registry.svc:5000/openshift/token?service=image-registry.openshift-image-registry.svc:5000&scope=repository:catalog-tests/console-java-simple:pull,push. Attempting again with no TLS verification.
[build : build-and-push] [INFO] Using base image with digest: sha256:e82def1a7b19c2801ac08b2defc29c4abddc81eaf981c089788b972a91743839
[build : build-and-push] [INFO] 
[build : build-and-push] [INFO] Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, org.eclipse.che.examples.HelloWorld]
[build : build-and-push] [INFO] 
[build : build-and-push] [INFO] Built and pushed image as image-registry.openshift-image-registry.svc:5000/catalog-tests/console-java-simple
[build : build-and-push] [INFO] 
[build : build-and-push] [INFO] ------------------------------------------------------------------------
[build : build-and-push] [INFO] BUILD SUCCESS
[build : build-and-push] [INFO] ------------------------------------------------------------------------
[build : build-and-push] [INFO] Total time:  21.734 s
[build : build-and-push] [INFO] Finished at: 2020-08-11T13:42:10Z
[build : build-and-push] [INFO] ------------------------------------------------------------------------
```

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Comment by sbwsg** [comment]
This seems like it would work but I think it's worth noting that the user's home directory is a constant in this YAML: it's always `/workspace` if I'm reading this right?  Does that not mean you could set the DOCKER_CONFIG env var to always be `/workspace/.docker`?  Tekton Pipelines *should* always initialize the credentials in the container's home directory.

**Comment by vdemeester** [comment]
> This seems like it would work but I think it's worth noting that the user's home directory is a constant in this YAML: it's always `/workspace` if I'm reading this right? Does that not mean you could set the DOCKER_CONFIG env var to always be `/workspace/.docker`? Tekton Pipelines _should_ always initialize the credentials in the container user's home directory.

@sbwsg we just need to set the `DOCKER_CONFIG` environment variable to a folder that has the `config.json`, it doesn't have to be in `/workspace/.docker`, or anything ; the `docker` command line (or thing following the same *pattern*) will use that env variable to get the configuration. Using `$(credentials.path)/.docker` guarantees us that, no matter where is `$HOME` set, no matter the configuration tekton is in, we will point to an existing folder :angel:

**Comment by sbwsg** [comment]
Ah, I see, gotcha thanks!

**Pull request merged**
