### PR TITLE
Bump tasks to v1beta1

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

**This is on `v1beta1-wip` so it won't affect `master` yet :wink:**

This port all task to `v1beta1` — kinda still a wip but :stuck_out_tongue_closed_eyes: 
<del>The tests should fail because we are still deploying the latest release (and not the 0.11-rcX)
/hold</del> (the script takes the latest release, so from today it should install 0.11.0-rc1 :stuck_out_tongue:)

/cc @sbwsg @bobcatfish 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by bobcatfish** [comment]
oooo there's some nice cleanup in there! :D

**Comment by skaegi** [comment]
I can do a pass to switch array use to use star expansion where appropriate once merged.

**Comment by vdemeester** [comment]
That would be :heart_eyes_cat: 
My follow-up is moving from GitResource to workspace and ImageResource to params :angel:

**Comment by vdemeester** [comment]
@afrittoli I did not, I just use `emacs` a little bit *smartly* :dancer:

**Comment by chmouel** [comment]
/approve

emacs rocks 😅

**Pull request merged**
