### PR TITLE
Make builpacks task Chains compliant

### PR DESCRIPTION
**Pull request by rgreinho**
Adds the Chains type hinting to the task to ensure it can be used by
Chains.

This problem came up based on the following issue in the Chains
repository
https://github.com/tektoncd/chains/issues/273#issuecomment-956411302.

### CODE REVIEW

**Comment by jromero** [comment]
Hi @rgreinho,

Thank you for the extra contribution here. Would you be opposed to making this change in https://github.com/buildpacks/tekton-integration? We'd love to tack on a few more things to an 0.4 release.

**Comment by rgreinho** [comment]
Absolutely no problem @jromero! 

Would that mean closing this issue?

**Comment by jromero** [comment]
> Absolutely no problem @jromero! 
> 
> Would that mean closing this issue? 

@rgreinho : Yes, we can handle everything on the other repo.

**Comment by rgreinho** [comment]
@jromero I copied my changes to https://github.com/buildpacks/tekton-integration/pull/34.

**Pull request closed without merging**
