### PR TITLE
Add proxy settings to kaniko task

### PR DESCRIPTION
**Pull request by micxer**
# Changes

Add proxy settings to kaniko task

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.

### CODE REVIEW

**Comment by chmouel** [comment]
Thanks for your contribution, i think we may want to think about this, if we are start adding those env variables we will need to add this to every tasks that does http requests.... I wonder if there is a better way to do this ?

**Comment by micxer** [comment]
Agreed. Now that you mentioned it, having a general way to do this might be better. I will have a look into [PodTemplates](https://github.com/tektoncd/pipeline/blob/master/docs/podtemplates.md) to see if that helps.

**Comment by chmouel** [comment]
@micxer i think it would be great if it doesn't to try to solve this directly in pipeline (as github.com/tektoncd/pipeline)

**Comment by vdemeester** [comment]
@micxer  switched the base branch to master as it got merged with `v1beta1` now :angel:

**Pull request closed without merging**
