### PR TITLE
Upgrade to buildah v1.31.0, pin by digest and add results to docs

### PR DESCRIPTION
**Pull request by jimmyjones2**
# Changes

New buildah 0.6 task: Upgrade to buildah v1.31.0, pin by digest and add results to docs

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations][authoring]
- [x] Includes [docs][docs] (if user facing)
- [x] Includes [tests][tests] (for new tasks or changed functionality)
  - See the [end-to-end testing documentation][e2e] for guidance and CI details.
- [x] Meets the [Tekton contributor standards][contributor] (including functionality, content, code)
- [x] Commit messages follow [commit message best practices][commit]
- [ ] Has a kind label. You can add one by adding a comment on this PR that
  contains `/kind <type>`. Valid types are bug, cleanup, design, documentation,
  feature, flake, misc, question, tep
- [x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md) for more details._

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]: https://github.com/tektoncd/catalog/issues/413
[authoring]: https://github.com/tektoncd/catalog/blob/main/recommendations.md
[docs]: https://github.com/tektoncd/community/blob/master/standards.md#docs
[tests]: https://github.com/tektoncd/community/blob/master/standards.md#tests
[e2e]: https://github.com/tektoncd/catalog/blob/main/CONTRIBUTING.md#end-to-end-testing
[contributor]: https://github.com/tektoncd/community/blob/main/standards.md
[commit]: https://github.com/tektoncd/community/blob/master/standards.md#commit-messages

### CODE REVIEW

**Review by vinamra28 — COMMENTED** [review]
@jimmyjones2 are there any breaking changes from `v1.23.3` to `v1.31.0` that we have to bump up the version of the task?

**Comment by jimmyjones2** [comment]
@vinamra28 Last time in #969 we decided to bump because it's not entirely clear with buildah. A quick look at the release notes show there are some things people might consider breaking, like in v1.29 --env no longer overrides ENV

**Comment by vinamra28** [comment]
> @vinamra28 Last time in #969 we decided to bump because it's not entirely clear with buildah. A quick look at the release notes show there are some things people might consider breaking, like in v1.29 --env no longer overrides ENV

ahh @jimmyjones2, thanks for reminding 😅 
can you please fix the linter and then we can merge this?

**Comment by jimmyjones2** [comment]
@vinamra28 Addressed the linter apart from `BUILD_EXTRA_ARGS` and `PUSH_EXTRA_ARGS` need to be unquoted as can contain extra multiple arguments.

**Comment by jimmyjones2** [comment]
@vinamra28 The tests are failing, but I don't think it's anything related to this change

**Comment by vdemeester** [comment]
Maybe it is related to https://github.com/containers/skopeo/issues/2096

**Comment by jimmyjones2** [comment]
Or shall I make it use the v1 tag, like skopeo #1190 - then don't need a PR for every new version :)

**Comment by jimmyjones2** [comment]
Have updated to use the `v1` tag. However the tests are still failing for something that looks unrelated and is breaking other integration tests:
> 2023/09/04 20:38:58 main.go:319: Something went wrong: encountered 2 errors: [error starting ./cluster/kubectl.sh --match-server-version=false version: exec: already started error during /home/prow/go/src/github.com/tektoncd/catalog/test/e2e-tests.sh --run-tests: exit status 1]

**Comment by jimmyjones2** [comment]
@vinamra28 @vdemeester Can you review again please?

**Comment by vinamra28** [comment]
@jimmyjones2 apologies, got occupied in some work. Can you please squash the commits ? 😅 
meanwhile let's see if the CI passes

**Comment by jimmyjones2** [comment]
@vinamra28 Still failing with the same error as before, which I don't think is anything to do with this change. Will squash in an hour or so

**Comment by vinamra28** [comment]
@jimmyjones2, CI is failing with error
```
Error: unknown flag: --cert-dir /workspace/sslcertdir
```

**Comment by jimmyjones2** [comment]
@vinamra28 Sorry, my bad. Fixed the issue and squashed

**Comment by jimmyjones2** [comment]
@vinamra28 Is this good to merge now?

**Comment by vinamra28** [comment]
@jimmyjones2 catlin is unhappy 😅 
`$(params.BUILD_EXTRA_ARGS)` and `$(params.PUSH_EXTRA_ARGS)` should be in quotes 😅

**Comment by jimmyjones2** [comment]
@vinamra28 They can't be in quotes as that's the way users pass multiple arbitrary arguments

**Comment by vinamra28** [comment]
in that case, can you please ask shellcheck to just ignore those lines, just add `# shellcheck disable=SC2046` before those lines

**Comment by jimmyjones2** [comment]
@vinamra28 Done. Can you kick off the integration test again please, prow looks to be having issues?

**Comment by jimmyjones2** [comment]
@vinamra28 Thanks! Looks as if it's always failing for everything :cry: - https://prow.tekton.dev/job-history/gs/tekton-prow/pr-logs/directory/pull-tekton-catalog-integration-tests

**Comment by vinamra28** [comment]
@jimmyjones2 will it be possible for you to rebase your PR over upstream/main as we have made some CI fixes so complete test suite is running in your PR

**Comment by jimmyjones2** [comment]
Thanks @vinamra28, we got there in the end 😄

**Comment by vinamra28** [comment]
yeah 😅, btw @jimmyjones2, ansible-builder is failing with latest version of buildah, can you please check and fix that?

**Comment by jimmyjones2** [comment]
@vinamra28 Is it this error? https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_catalog/1200/pull-tekton-catalog-integration-tests/1703056376193880064#1:build-log.txt%3A4029 How would I know this is from buildah rather than git-clone?

**Comment by vinamra28** [comment]
> @vinamra28 Is it this error? https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_catalog/1200/pull-tekton-catalog-integration-tests/1703056376193880064#1:build-log.txt%3A4029 How would I know this is from buildah rather than git-clone?

well, I tried reproducing on my machine and I think that the fix for the issue can be fixed in https://github.com/tektoncd/catalog/pull/1200/commits/c03abbee0c01e79e22c87206e41d9b7138984cb7, can you please validate?

**Comment by jimmyjones2** [comment]
@vinamra28 I agree. Hadn't appreciated `${CERT_DIR_FLAG}` could be empty, which when quoted would pass an empty argument

**Comment by jimmyjones2** [comment]
@vinamra28 Shall I raise a new PR to fix?

**Comment by vinamra28** [comment]
@jimmyjones2, no need, just check if https://github.com/tektoncd/catalog/pull/1200/commits/2d4f3980090d7d8a1643edbce0b2ebd8fec8bdef should be good enough?

**Comment by jimmyjones2** [comment]
@vinamra28 Still gives the same error, because even though `CERT_DIR_FLAG` is defined, `"${CERT_DIR_FLAG}"` results in an empty argument.

Removing the quotes around `${CERT_DIR_FLAG}` does the trick for me:
```
    script: |
      [ "$(workspaces.sslcertdir.bound)" = "true" ] && CERT_DIR_FLAG="--cert-dir=$(workspaces.sslcertdir.path)"
      [ "$(workspaces.dockerconfig.bound)" = "true" ] && DOCKER_CONFIG="$(workspaces.dockerconfig.path)" && export DOCKER_CONFIG
      # shellcheck disable=SC2046
      buildah ${CERT_DIR_FLAG} "--storage-driver=$(params.STORAGE_DRIVER)" bud $(params.BUILD_EXTRA_ARGS) \
        "--format=$(params.FORMAT)" "--tls-verify=$(params.TLSVERIFY)" --no-cache \
        -f "$(params.DOCKERFILE)" -t "$(params.IMAGE)" "$(params.CONTEXT)"
      [ "$(params.SKIP_PUSH)" = "true" ] && echo "Push skipped" && exit 0
      # shellcheck disable=SC2046
      buildah ${CERT_DIR_FLAG} "--storage-driver=$(params.STORAGE_DRIVER)" push $(params.PUSH_EXTRA_ARGS) \
        "--tls-verify=$(params.TLSVERIFY)" --digestfile /tmp/image-digest "$(params.IMAGE)" \
        "docker://$(params.IMAGE)"
      tee "$(results.IMAGE_DIGEST.path)" < /tmp/image-digest
      printf '%s' "$(params.IMAGE)" | tee "$(results.IMAGE_URL.path)"
```

**Pull request merged**
