### PR TITLE
Add platforms information for helm-upgrade-from-repo and helm-upgrade-from-source tasks

### PR DESCRIPTION
**Pull request by barthy1**
# Changes
Following [TEP 70](https://github.com/tektoncd/community/blob/main/teps/0070-tekton-catalog-task-platform-support.md), information about platforms, on which tasks can be run, is added.
Tested for `linux/amd64`, `linux/s390x`, `linux/ppc64le` platforms using e2e test provided with tasks.

Also helm image is updated to use multi-arch version of it.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by fhopfensperger** [comment]
@barthy1 Thx for the PR. 
Do you have a chance to test it on `linux/arm64` ? Because then we could add it.

**Comment by barthy1** [comment]
@fhopfensperger 
>Do you have a chance to test it on linux/arm64 ? Because then we could add it.

No, unfortunately I don't have arm64 hardware to do that test :( 
The proposed helm image has `linux/arm64` support. Here I think it's up to task owners, if linux/arm64 can be added to the platform list based on image support info, but without tests.

**Comment by fhopfensperger** [comment]
Today I had the chance to test the tasks on my local raspberry pi (arm64) cluster. Everything worked as expected, only the pod of `helm repo task` obviously cannot be started as the used `envoy` deployment doesn't support `arm64`.

@barthy1 If you like you can add the `arm64` annotation. I would then take care of the other thing, unless you want to do it?

**Comment by barthy1** [comment]
@fhopfensperger annotations and READMEs are extended with `linux/arm64`

**Comment by fhopfensperger** [comment]
/lgtm
Thank you!

**Review by fhopfensperger — APPROVED** [review]

**Pull request merged**
