### PR TITLE
fix(buildah): makes it able to overwrite --tls-verify on push

### PR DESCRIPTION
**Pull request by daper**
# Changes

This PR makes it able to overwrite `--tls-verify` on push. It moves to the end of the command the variable `PARAM_PUSH_EXTRA_ARGS`. Otherwise you will have to disable `TLSVERIFY` for pull actions too and that is not desirable. This way one can run the action with the parameter `PUSH_EXTRA_ARGS=--tls-verify=false` and being able to push to an insecure registry. But still maintaining the TLS checks on build.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations][authoring]
- [x] Includes [docs][docs] (if user facing)
- [x] Includes [tests][tests] (for new tasks or changed functionality)
  - See the [end-to-end testing documentation][e2e] for guidance and CI details.
- [x] Meets the [Tekton contributor standards][contributor] (including functionality, content, code)
- [x] Commit messages follow [commit message best practices][commit]
- [x] Has a kind label. You can add one by adding a comment on this PR that
  contains `/kind <type>`. Valid types are bug, cleanup, design, documentation,
  feature, flake, misc, question, tep
- [x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md) for more details._

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]: https://github.com/tektoncd/catalog/issues/413
[authoring]: https://github.com/tektoncd/catalog/blob/main/recommendations.md
[docs]: https://github.com/tektoncd/community/blob/master/standards.md#docs
[tests]: https://github.com/tektoncd/community/blob/master/standards.md#tests
[e2e]: https://github.com/tektoncd/catalog/blob/main/CONTRIBUTING.md#end-to-end-testing
[contributor]: https://github.com/tektoncd/community/blob/main/standards.md
[commit]: https://github.com/tektoncd/community/blob/master/standards.md#commit-messages

### CODE REVIEW

**Comment by vinamra28** [comment]
> Diff between version 0.8 and 0.9
> ```diff
> diff --git a/task/buildah/0.8/README.md b/task/buildah/0.9/README.md
> index aa5047c..4ac13c1 100644
> --- a/task/buildah/0.8/README.md
> +++ b/task/buildah/0.9/README.md
> @@ -10,7 +10,7 @@ to assemble a container image, then pushes that image to a container registry.
>  ## Install the Task
>  
>  ```
> -kubectl apply -f https://api.hub.tekton.dev/v1/resource/tekton/task/buildah/0.8/raw
> +kubectl apply -f https://api.hub.tekton.dev/v1/resource/tekton/task/buildah/0.9/raw
>  ```
>  
>  ## Parameters
> diff --git a/task/buildah/0.8/buildah.yaml b/task/buildah/0.9/buildah.yaml
> index 7866810..91e087b 100644
> --- a/task/buildah/0.8/buildah.yaml
> +++ b/task/buildah/0.9/buildah.yaml
> @@ -4,7 +4,7 @@ kind: Task
>  metadata:
>    name: buildah
>    labels:
> -    app.kubernetes.io/version: "0.8"
> +    app.kubernetes.io/version: "0.9"
>    annotations:
>      tekton.dev/categories: Image Build
>      tekton.dev/pipelines.minVersion: "0.50.0"
> @@ -114,9 +114,9 @@ spec:
>        [ "${PARAM_SKIP_PUSH}" = "true" ] && echo "Push skipped" && exit 0
>        # push the image (CERT_DIR_FLAG should be omitted if empty and PUSH_EXTRA_ARGS can contain multiple args)
>        # shellcheck disable=SC2046,SC2086
> -      buildah ${CERT_DIR_FLAG} "--storage-driver=${PARAM_STORAGE_DRIVER}" push ${PARAM_PUSH_EXTRA_ARGS} \
> -        "--tls-verify=${PARAM_TLSVERIFY}" --digestfile /tmp/image-digest "${PARAM_IMAGE}" \
> -        "docker://${PARAM_IMAGE}"
> +      buildah ${CERT_DIR_FLAG} "--storage-driver=${PARAM_STORAGE_DRIVER}" push \
> +        "--tls-verify=${PARAM_TLSVERIFY}" --digestfile /tmp/image-digest ${PARAM_PUSH_EXTRA_ARGS} \
> +        "${PARAM_IMAGE}" "docker://${PARAM_IMAGE}"
>        tee "$(results.IMAGE_DIGEST.path)" < /tmp/image-digest
>        printf '%s' "${PARAM_IMAGE}" | tee "$(results.IMAGE_URL.path)"
>      volumeMounts:
> ```

hi @daper, I can see that we have just reordered the arguments. Was wondering if we should be bumping up the version of the task in such cases 🤔 
@vdemeester @daper please let me know your thoughts on this

**Comment by daper** [comment]
> @vdemeester @daper please let me know your thoughts on this

hi @vinamra28! I am of the thinking that even for the smallest change it should be a version bump, patch if you want, but version needs to reflect it. That said, I don't have a strong opinion here, so I am fine either way.

**Comment by vinamra28** [comment]
> > @vdemeester @daper please let me know your thoughts on this
> 
> hi @vinamra28! I am of the thinking that even for the smallest change it should be a version bump, patch if you want, but version needs to reflect it. That said, I don't have a strong opinion here, so I am fine either way.

@daper, is the current version of the task breaking? If so, then we should fix this else we can go ahead and bump up the version.

**Comment by daper** [comment]
> @daper, is the current version of the task breaking? If so, then we should fix this else we can go ahead and bump up the version.

No, it's not really breaking anything. But if you try to push to an insecure registry, you need to turn it off for pulling too; as the order of the flags for pushing makes it so. I'd rather call it a zero-effort-feature (?) :sweat_smile:.

**Pull request merged**
