### PR TITLE
Telemetry support in RH-CRDA task.

### PR DESCRIPTION
**Pull request by jparsai**
# Changes

To collect telemetry data about use of CRDA services, user consent is added into Secrets and task is modified to inform CRDA platform about consumer of services.
As it requires changes in Task and Secret a new version is released. 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Review by vinamra28 — CHANGES_REQUESTED** [review]
hi @jparsai, I guess the following changes may affect the existing users using this task. Can you please bump the new version of the task?

**Comment by jparsai** [comment]
> hi @jparsai, I guess the following changes may affect the existing users using this task. Can you please bump the new version of the task?

Hi @vinamra28, this will not cause any issue for existing users, as in CRDA side this feature is backward compatible, means if a existing user not having new secret or using old Tekton task still it will run without any issues. I have tested that scenario as well.
Is it still required to release a new version?

**Comment by jparsai** [comment]
Okay to avoid any confusion to users, I will create a new version of task.

**Comment by jparsai** [comment]
A new version 0.2 is added, following files are different than 0.1 version.
```
0.2/redhat-codeready-dependency-analysis.yaml
0.2/README.md
0.2/samples/secret.yaml
0.2/tests/pipeline-run.yaml
```

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Comment by jparsai** [comment]
Hey there,
In order to get approval, am I supposed to do something in this PR? which I missed or is it simply in queue for approval and I should wait for queue to be cleared.

**Comment by jparsai** [comment]
Kindly provide required labels, performed rebase to pull latest code from upstream repository.

**Pull request closed without merging**
