### PR TITLE
Add npm cli task

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

This task can be used to run npm goals on a nodejs based project.

Signed-off-by: vinamra28 <vinjain@redhat.com>
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [X] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [X] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [X] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [X] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [X] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [X] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by chmouel** [comment]
It takes 5mn to run the test : 

```
16h00:29 STARTING: npm/0-1
16h00:29::16h05:00 SUCCESS: npm/0-1 testrun has successfully executed
```

Usually long running (as over a minute) test have a high probability of flakyness, specially for thing like npm who pulls out a lot of files everywhere (ie like mvn)

any chances to get a smaller repo for testing?

The goal of the test is to test the task not to test if the actual "flakes" it :) 

/hold

**Comment by vinamra28** [comment]
@chmouel I have changed the repository for test and now it takes around 1mn
```
15h31:32::15h32:38 SUCCESS: npm/0-1 testrun has successfully executed
```
Does this look good to you?

**Comment by chmouel** [comment]
wonderful thank you!

/lgtm

Looking Good! 🤙🏽

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
