### PR TITLE
Fix/191 fix cache dir arg

### PR DESCRIPTION
**Pull request by ameyer-pivotal**
# Changes

- Added missing `cache-dir` arg to `analyze` step
- Added test

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by ameyer-pivotal** [comment]
By the way, please don't merge yet. We want to add to the test a bit, but we wanted the simple version of the tests to run first.

**Comment by vdemeester** [comment]
> By the way, please don't merge yet. We want to add to the test a bit, but we wanted the simple version of the tests to run first.

you can use `/hold` to make sure it doesn't get merge (and `/hold cancel` to remove the hold).
/hold

**Pull request merged**
