### PR TITLE
Update catalog e2e test runner to use Pipelines v0.25.0

### PR DESCRIPTION
**Pull request by jerop**
Pipelines just released v0.25.0.

This commit updates the e2e test runner to use the new version
of Pipelines when testing catalog entries.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md) for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]

**Comment by chmouel** [comment]
That ansible-runner test is really too flaky :

```
fatal: [localhost]: FAILED! => {"changed": false, "error": "No module named 'kubernetes'", "msg": "Failed to import the required Python library (openshift) on ansibler-runner-pipeline-run-ansible-runner-run-8z4sg-pod-zn9th's Python /usr/bin/python3.6. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

it tries to get a lot of stuff externally,

@kameshsampath is there any chance to change the example repo in the ansible runner test to something that is more simple and contained ? which mean the less external dependencies as possible (ie: be it a unit test not an sample)

**Comment by kameshsampath** [comment]
@chmouel  - I could try that, let me work on it and update back here.

**Comment by vinamra28** [comment]
ansible runner task requires HOME env to be set
```
diff --git a/task/ansible-runner/0.1/ansible-runner.yaml b/task/ansible-runner/0.1/ansible-runner.yaml
index 3a58a57..82b4fde 100644
--- a/task/ansible-runner/0.1/ansible-runner.yaml
+++ b/task/ansible-runner/0.1/ansible-runner.yaml
@@ -29,6 +29,9 @@ spec:
         - --help
   steps:
     - name: requirements
+      env:
+      - name: HOME
+        value: /tekton/home
       image: docker.io/ansible/ansible-runner:1.4.6@sha256:bd09ef403f2f90f2c6bd133d7533e939058903f69223c5f12557a49e3aed14bb #tag: 1.4.6
       script: |
         #!/bin/bash
@@ -50,6 +53,9 @@ spec:
       workingDir: '$(workspaces.runner-dir.path)/$(params.project-dir)'
 
     - name: run-playbook
+      env:
+      - name: HOME
+        value: /tekton/home
       image: docker.io/ansible/ansible-runner:1.4.6@sha256:bd09ef403f2f90f2c6bd133d7533e939058903f69223c5f12557a49e3aed14bb #tag: 1.4.6
       command: ['entrypoint']
       args:
```
I tried to add the above and it worked
cc @chmouel @jerop

**Comment by chmouel** [comment]
@vinamra28 can you submit it so we can merge this?

**Comment by vinamra28** [comment]
> @vinamra28 can you submit it so we can merge this? (i think this should be in another PR ?)

sure. I can raise another PR which can have all the fixes

**Pull request merged**
