### PR TITLE
Add dependabot configuration.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

See
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

I think this should also update yaml manifests, though not 100% about this.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations][authoring]
- [ ] Includes [docs][docs] (if user facing)
- [ ] Includes [tests][tests] (for new tasks or changed functionality)
  - See the [end-to-end testing documentation][e2e] for guidance and CI details.
- [x] Meets the [Tekton contributor standards][contributor] (including functionality, content, code)
- [x] Commit messages follow [commit message best practices][commit]
- [x] Has a kind label. You can add one by adding a comment on this PR that
  contains `/kind <type>`. Valid types are bug, cleanup, design, documentation,
  feature, flake, misc, question, tep
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md) for more details._

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]: https://github.com/tektoncd/catalog/issues/413
[authoring]: https://github.com/tektoncd/catalog/blob/main/recommendations.md
[docs]: https://github.com/tektoncd/community/blob/master/standards.md#docs
[tests]: https://github.com/tektoncd/community/blob/master/standards.md#tests
[e2e]: https://github.com/tektoncd/catalog/blob/main/CONTRIBUTING.md#end-to-end-testing
[contributor]: https://github.com/tektoncd/community/blob/main/standards.md
[commit]: https://github.com/tektoncd/community/blob/master/standards.md#commit-messages

### CODE REVIEW

**Review by vinamra28 — COMMENTED** [review]
thanks @wlynch, for raising this PR. I wonder if:
1. this gonna work for Tekton tasks
2. we should be maintaining the images of Tasks present in this catalog? Since we have github.com/tektoncd-catalog as the official catalog, shouldn't we try to maintain those tasks?
/cc @vdemeester @jerop

**Comment by wlynch** [comment]
> 1. this gonna work for Tekton tasks

Not 100%, but based on https://github.com/dependabot/dependabot-core/blob/5120469e108e343a030ffc7159e23150d025a7d4/docker/lib/dependabot/docker/file_fetcher.rb#L73-L76 I think it will.

Worst case this does nothing and we're in the same position we're already in. 🤷 

> 2. we should be maintaining the images of Tasks present in this catalog? Since we have github.com/tektoncd-catalog as the official catalog, shouldn't we try to maintain those tasks?

Until this repo is archived, it's still worth doing (we should also do this in any new repos).

There are a lot of images we're including in here which are out of date because we're pinning to versions and not updating them. For example, I updated the git image in https://github.com/tektoncd/catalog/pull/1129 because it had several critical severity vulnerabilities, but since then there's already been more critical vulnerabilities reported upstream in Git that we haven't pulled in fixes for yet. 

This is intended to help us pull in new images via automation so we're not letting old images rot with vulnerabilities.

**Review by vinamra28 — APPROVED** [review]

**Comment by wlynch** [comment]
Few observations from this after seeing it run:

- Looks like we need to configure this per directory 
- [Dependabot only looks at fields named `image`](https://github.com/dependabot/dependabot-core/blob/ae8daf1de100ee81374e3098f1f0d1cdec607325/docker/lib/dependabot/docker/file_parser.rb#L209)

😭 

Some form of this would be nice to have. Not sure if we want to tweak catalog best practices or write our own tool to be more flexible though 🤷

**Pull request merged**
