### PR TITLE
added 0.1 of pluto task

### PR DESCRIPTION
**Pull request by garethahealy**
# Changes

Added a new task to run `pluto`
- https://pluto.docs.fairwinds.com/

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Review by vinamra28 — COMMENTED** [review]
can you please add some tests as well?
Also I can see that there is one more PR #767 similar to this one. Probably you can take some reference from that PR and once this PR gets merged will close the other one as the author of PR isn't active anymore.

**Comment by garethahealy** [comment]
@vinamra28 pushed requested changes.

re: the other PR. I'd not seen it, but that PR takes a more opinionated view (i.e.: more args on what can be done/not done), my PR just gives you access to the binary and you do whatever you want with it.

**Comment by garethahealy** [comment]
@vinamra28 need anymore changes / input from me or good to merge?

**Review by vinamra28 — COMMENTED** [review]
hey :wave:, sorry for the late response :sweat_smile: 
/approve

**Comment by garethahealy** [comment]
@vinamra28 ; anything else needed to get this merged?

**Comment by vinamra28** [comment]
> @vinamra28 ; anything else needed to get this merged?

hey @garethahealy, just waiting for someone else to review this as well

**Pull request merged**
