### PR TITLE
Update minimum pipeline version to v0.29.0 for task git-clone

### PR DESCRIPTION
**Pull request by bradbeck**
# Changes

The Kyverno `verify-image` policy fails to verify the signature on `v0.21.0`:
```
task fetch-from-git has failed: failed to create task run pod "cache-image-pipelinerun-z6j99-fetch-from-git-vnmbv": admission webhook "mutate.kyverno.svc-fail" denied the request: 

resource Pod/default/cache-image-pipelinerun-z6j99-fetch-from-git-vnmbv-pod-dl755 was blocked due to the following policies

verify-image:
  verify-image: 'image signature verification failed for gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.21.0:
    signature mismatch'
. Maybe missing or invalid Task default/git-clone
```

Essentially a copy of the 0.4 version with the pipeline version minimum changed to v0.29.0.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by piyush-garg** [comment]
@bradbeck Any reason to bump the git-clone version? We are just changing the git-init from 0.21 o 0.29. Will it break if used with 0.21?

**Comment by bradbeck** [comment]
> @bradbeck Any reason to bump the git-clone version? We are just changing the git-init from 0.21 o 0.29. Will it break if used with 0.21?

From what I understand, the 0.21 pipeline artifacts are not signed in a way that the Kyverno`verify-image` policy finds acceptable. We've found (as part of our work on https://github.com/thesecuresoftwarefactory/ssf) that we need to use 0.29 for the pipeline artifacts to make things work.

**Comment by bradbeck** [comment]
@chmouel @imjasonh Any suggests on what I can do to move this forward?

**Comment by chmouel** [comment]
/cc @tektoncd/cli-collaborators  @sbwsg 

PTAL

**Review by vdemeester — COMMENTED** [review]
/ok-to-test

**Pull request merged**
