### PR TITLE
Add a test for the kubeconfig-creator task

### PR DESCRIPTION
**Pull request by chmouel**
# Changes

Add a test for the kubeconfig-creator task

### CODE REVIEW

**Comment by piyush-garg** [comment]
Test is failing

```sh
{"level":"fatal","ts":1602013552.0897691,"logger":"fallback-logger","caller":"kubeconfigwriter/main.go:115","msg":"Error writing kubeconfig to file: open /workspace/output/kubeconfig: permission denied","commit":"4e23d50","stacktrace":"main.createKubeconfigFile\n\tgithub.com/tektoncd/pipeline/cmd/kubeconfigwriter/main.go:115\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/kubeconfigwriter/main.go:52\nruntime.main\n\truntime/proc.go:203"}
```

**Comment by chmouel** [comment]
yep it's weird, it doesnt fail when running it locally... not sure why the volume is not writable here..

**Review by Divyansh42 — COMMENTED** [review]
Can we modify the kubeconfig-creator task? as after the change task will not produce [this](https://github.com/tektoncd/catalog/pull/535#issuecomment-704720088) error.

May be we can add something like this to resolve write permission issue
```
securityContext:
        runAsUser: 0
```

Then probably we can write some better tests, because presently we are not testing much things :sweat_smile:

**Review by Divyansh42 — APPROVED** [review]
I think running the task as root user will not be a good approach.
So this PR is fine for me.

**Review by piyush-garg — APPROVED** [review]
/lgtm

**Pull request merged**
