### PR TITLE
Use latest release for e2e tests

### PR DESCRIPTION
**Pull request by lbernick**
# Changes
This commit updates the catalog e2e tests to use the latest Pipelines release.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- n/a Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- n/a Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- n/a Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- n/a Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]

### CODE REVIEW

**Comment by lbernick** [comment]
@tektoncd/catalog-maintainers is there an easy way to update catalog tasks to v1beta1 (or create a new version with v1beta1 instead of v1alpha1 and run e2e tests only on the v1beta1 version)? that's why this PR is failing

**Comment by vinamra28** [comment]
@lbernick probably you can add an annotation `tekton.dev/deprecated: true` on all the resources' versions which are using v1alpha1 APIs. CI will detect the annotation and skip the tests. Also you can bump the version of the respective Tasks to use v1beta1 APIs.

**Comment by lbernick** [comment]
Thanks @vinamra28! is there some way of automating this? (I think bumping the version would also require adding a new catalog task version so I might do that separately)

**Comment by vinamra28** [comment]
> Thanks @vinamra28! is there some way of automating this? (I think bumping the version would also require adding a new catalog task version so I might do that separately)

@lbernick, I just checked, `v1alpha1` APIs are being used in samples and tests only. None of the Task is using v1alpha1 APIs, do version bump is not required. 

To answer your question

> is there some way of automating this?

Not as of now

**Review by vinamra28 — APPROVED** [review]
/lgtm

**Pull request merged**
