### PR TITLE
Add Tasks to install Tekton Pipelines itself 🤯

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

As part of #373 I'm continuing to create Tasks that we can use to run
tests for items in the catalog.

The goal of the 2 Tasks in this commit is to install Tekton Pipelines into a
cluster that was created using the Task added in #436.

There are a couple of options different from what I did in this commit
which I'd like people's opinions on:
1. I went to a lot of trouble to make it so that Pipelines can be
   installed with just a kubectl command, specifically creating a user
   with cluster admin priviledges. If instead I used a container with
   gcloud, I could use the same approach as other GKE specific Tasks,
   but I wanted to make the install Task not tied to GKE. I also had
   to give the prow-account more priviledges in all of our boskos
   projects for this to work 😬 . So my question is: is this worth
   it, or am I better off just creating a GKE specific Task for
   installing Tekton Pipelines that uses gcloud to auth?
2. If we DO want a super generic Task, how useful is this Task that just
   applies a Tekton yaml? Would we be better off with a generic kubectl
   task that I could feed the exact arguments for installing Tekton
   Pipelines?

The other confusion I ran into here (which I am going to follow up with
@sbwsg about!) is around service accounts vs. secrets. The GKE Tasks
I've made so far rely on secrets provided via workspaces, but I feel
like it's not clear if it makes sense to go that route, or to rely on
service accounts. In the meantime this approach is at least consistent
with #436.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Yaml file complies with [yamllint](https://github.com/adrienverge/yamllint) rules.
- [x] Complies with [Catalog Orgainization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by bobcatfish** [comment]
Interested in your thoughts on the 2 questions above @dlorenc @vdemeester @sbwsg @afrittoli  ^^

**Comment by bobcatfish** [comment]
```
+ echo 'FAILED: docker-build task has failed to comeback properly'
FAILED: docker-build task has failed to comeback properly
```

a flake maybe? 🤔

**Comment by afrittoli** [comment]
@bobcatfish I will look into this once I'm back. Just FYI - this is what we use today to install Tekton (pipeline, trigger and dashboard) to the `robocat` and `dogfooding` clusters today: https://github.com/tektoncd/plumbing/blob/master/tekton/resources/release/install_tekton_release.yaml - it uses the release yaml but it adds the ability to use `kustomize` overlays from a git repo on top. I find that would be useful for test purposes too, since one might want to test different configurations of the tekton services in E2E tests.

**Comment by bobcatfish** [comment]
Thanks @afrittoli ! i probably wont get a change to make sweeping changes to this until next week but it looks like im better off using the Tasks youve already created

when you get a chance could you explain a bit more about the overlays you need? i'm also wondering how the Task is supplied with the credentials it needs, is that via the service account?

**Comment by bobcatfish** [comment]
/hold

want to integrate in the Tasks @afrittoli has already created for this: https://github.com/tektoncd/plumbing/blob/master/tekton/resources/release/install_tekton_release.yaml

**Comment by bobcatfish** [comment]
I'll just close this for now actually to reduce the noise :D

**Pull request closed without merging**
