### PR TITLE
[TEP-0110] Update Tekton Catalog installation instructions

### PR DESCRIPTION
**Pull request by QuanZhang-William**
# Changes
Prior to this change, the installation instructions directly use the resource urls in the Catalog repo, which results in tight coupling between the organization and how users fetch resources (as described in TEP-0110). This commit updates the installation guide to install Tekton Catalog resources via Tekton Hub Api: https://github.com/tektoncd/hub/pull/539

This change decouples the Tekton Catalog organization from resouces resolution, which enables Tekton Catalog reorganization.

# Todo
- [x] Hold till https://github.com/tektoncd/hub/pull/539 gets released
- [x] Confirm details about the change format

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

### CODE REVIEW

**Comment by vinamra28** [comment]
keeping on hold as this requires a new release of Hub v1.9.0
/hold

**Review by jerop — APPROVED** [review]
Thank you @QuanZhang-William!

**Comment by jerop** [comment]
This PR should be ready to go now that the Hub is released -- https://api.hub.tekton.dev/v1/resource/tekton/task/git-clone/0.5/raw

@QuanZhang-William please fetch the latest changes merged in main and update installation instructions for those new resources as well 🙏🏾

**Comment by QuanZhang-William** [comment]
> This PR should be ready to go now that the Hub is released -- https://api.hub.tekton.dev/v1/resource/tekton/task/git-clone/0.5/raw
> 
> @QuanZhang-William please fetch the latest changes merged in main and update installation instructions for those new resources as well 🙏🏾

@jerop Thanks for the reminder, I have updated the instructions for new resources

**Comment by PuneetPunamiya** [comment]
Thanks for the patch 🤗 
/lgtm

**Comment by jerop** [comment]
@PuneetPunamiya I don't have approval access in this repo, so switch places?

/lgtm

**Comment by vinamra28** [comment]
@jerop even he doesn't have 😝
/approve

**Comment by jerop** [comment]
thanks @vinamra28

**Pull request merged**
