### PR TITLE
Add version 0.2 to terraform-cli task

### PR DESCRIPTION
**Pull request by ttretau**
# Changes

- Add parameter for the Terraform image
- Add proxy parameter
- Use official Hashicorp Terraform by default
- Better Terraform Environment Variable description

### CODE REVIEW

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Comment by chmouel** [comment]
SGTM

the diff between the two versions for other reviewers : 

https://paste.gg/p/anonymous/494168b24dd648609db460f712757af1

/lgtm
/approve

**Pull request merged**
