### PR TITLE
Fix Kamel-run issue with parameters

### PR DESCRIPTION
**Pull request by gansheer**
Fix the issue when parameters are provided to the kamel-run task.

Example of error with `container-image` param:
```
Error: cannot read sources: failed to resolve sources: missing file or unsupported scheme in examples/yaml/data/routes.yaml -t container.image=10.111.155.196/default/exampleyaml@sha256:06398e857e71463bf235623529d35b908ff1b835e51775e3ad119feb674c918d
```

# Changes

Define the command parameters as an array instead of a string in the run command arguments because the it interprets the string as a single parameter.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Follows the [authoring recommendations][authoring]
- [ ] Includes [docs][docs] (if user facing)
- [ ] Includes [tests][tests] (for new tasks or changed functionality)
  - See the [end-to-end testing documentation][e2e] for guidance and CI details.
- [X] Meets the [Tekton contributor standards][contributor] (including functionality, content, code)
- [X] Commit messages follow [commit message best practices][commit]
- [ ] Has a kind label. You can add one by adding a comment on this PR that
  contains `/kind <type>`. Valid types are bug, cleanup, design, documentation,
  feature, flake, misc, question, tep
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md) for more details._

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]: https://github.com/tektoncd/catalog/issues/413
[authoring]: https://github.com/tektoncd/catalog/blob/main/recommendations.md
[docs]: https://github.com/tektoncd/community/blob/master/standards.md#docs
[tests]: https://github.com/tektoncd/community/blob/master/standards.md#tests
[e2e]: https://github.com/tektoncd/catalog/blob/main/CONTRIBUTING.md#end-to-end-testing
[contributor]: https://github.com/tektoncd/community/blob/main/standards.md
[commit]: https://github.com/tektoncd/community/blob/master/standards.md#commit-messages

### CODE REVIEW

**Review by squakez — APPROVED** [review]

**Review by vinamra28 — COMMENTED** [review]
will it be possible for you to add a test case for the same?

**Comment by gansheer** [comment]
> will it be possible for you to add a test case for the same?

I fixed the existing test case (that produced a false positive) and added a new one for this error case.

**Comment by gansheer** [comment]
@vinamra28 please review :)

**Review by vinamra28 — CHANGES_REQUESTED** [review]
@gansheer PR looks good, can you please have proper commit messages as our PR merge strategy is `rebase and merge` so commit messages should be descriptive enough 😅

**Comment by gansheer** [comment]
> @gansheer PR looks good, can you please have proper commit messages as our PR merge strategy is `rebase and merge` so commit messages should be descriptive enough 😅

@vinamra28  I changed the commit messages, I hope I understood the [the best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages) correctly. If I missed anything from  please don't hesitate to tell me where the change is needed :pray: .

**Comment by vinamra28** [comment]
thanks @gansheer for doing this, commit messages looks fine now
/test pull-tekton-catalog-integration-tests

**Review by vinamra28 — APPROVED** [review]
/lgtm

**Pull request merged**
